#include <iostream>
#include <cstringt.h> // FOR BYTE TYPE UINT TYPE....
#include "./modules/calcula.h"
#include "./modules/calculo_0.h"
#include "./modules/calculo_2.h"
#include "./modules/calculo_3.h"
#include "./modules/calculo_4.h"
#include "./modules/calculo_5.h"
#include "./modules/calculo_6.h"
#include "./modules/calculo_7.h"

/*
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXKK00XWMMMMMMMMMMMMMMMMMMMMMWNXXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0OkxdoolllldKWMMMMMMMMMMMMMMMMMMMWKOkkkOO00KKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xolccccccccllllxKWMMMMMMMMMMMMMMMMMWKOkkkkkkkkkOOO0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKxlc:::::cccccllllloxXMMMMMMMMMMMMMMMMWXOkkkkOOOOOOOOOOOOO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdc:::::::cccccllllloooONMMMMMMMMMMMMMMMN0kkkOOOOOOOOOOOOOOOOO0KNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl:::::::::ccccclllllooodKWMMMMMMMMMMMMMWKkkkOOOOOOO000000OOOOOOO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd::::::::::cccccclllllooookXMMMMMMMMMMMMMXOkkOOOOOO0000000000OOOOOOOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo:::::::::::cccccllllllooood0WMMMMMMMMMMMW0kkkOOOOO000000000000OOOOOkOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXd::::::::::::ccccclllllloooodkXMMMMMMMMMMWXOkkkOOOOO000000000000OOOOOkkOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc::::::::::::cccccclllllooooodKWMMMMMMMMMW0kkkkOOOOOO0000000000OOOOOOkkkOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo::::::::::::::ccccclllllloooodONMMMMMMMMMNOkkkkkOOOOOOO000000OOOOOOOkkkkkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKk0NMMMMMMMMMMMMMMMM0l::::::::::::::ccccclllllloooooxXWMMMMMMMWKkkkkkkkOOOOOOOOOOOOOOOOOOkkkkkk0NMMMMMMMMMMMMMMMMN00NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxc;cdKWMMMMMMMMMMMMMM0l::::::::::::::ccccclllllloooood0WMMMMMMMW0xxkkkkkkkOOOOOOOOOOOOOOkkkkkkkx0NMMMMMMMMMMMMMMWKxlld0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOl:;;;:lkNWMMMMMMMMMMMM0l:::::::::::::::ccccclllllooooodONMMMMMMMXOxxxxkkkkkkkkkkkkkkkkkkkkkkkkkxx0WMMMMMMMMMMMMWXOolllllxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd:;;;;;;;:dKWMMMMMMMMMMMKo:::::::::::::::ccccccllllloooookXMMMMMMWKkxxxxxkkkkkkkkkkkkkkkkkkkkkkxxxx0WMMMMMMMMMMMWKxollllccclkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl;;;;;;;;;;;lkNWMMMMMMMMMNx::::::::::::::::cccccllllllooooxKWMMMMMW0xxxxxxxxxkkkkkkkkkkkkkkkkxxxxxxkKWMMMMMMMMMWXOdlllllccccccdKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc;;;;;;;;;;;;;:dKWMMMMMMMMWOl::::::::::::::::ccccclllllloood0WMMMMMNOddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxONMMMMMMMMMWKxolllllcccccc::lOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx:;;;;;;;;;;;;;;;:lONMMMMMMMMNd:::::::::::::::::ccccclllllllooONMMMMMXkdddddxxxxxxxxxxxxxxxxxxxxxxxxxx0WMMMMMMMWNOdllllllcccccc::::lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx:;;;;;;;;;;;;;;;;;;cxXWMMMMMMW0l:::::::::::::::::ccccclllllllokNMMMMMXxdddddddddxxxxxxxxxxxxxxxxdddddONMMMMMMMWKxollllllcccccc::::::lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:;;;;;;;;;;;;;;;;;;;;:o0NMMMMMMNxc:::::::::::::::::ccccccllllllxXMMMMMKxoodddddddddddddddddddddddddddxKWMMMMMMN0dolllllccccccc::::::::l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c;;;;;;;;;;;;;;;;;;;;;;:ckXMMMMMWXd::::::::::::::::::ccccccclllldKWMMMW0dooooodddddddddddddddddddddddd0NMMMMMWXkollllllcccccc:::::::::::dKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd;;;;;;;;;;;;;;;;;;;;;;;;;:dKWMMMMW0l:::::::::::::::::::ccccccllldKWMMMWOoooooooooooddddddddddddddooodkNMMMMMWKxlllllllcccccc::::::::::::ckWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0l;;;;;;;;;;;;;;;;;;;;;;;;;;:lONMMMMWOl:::::::::::::::::::ccccccclo0WMMMWOolloooooooooooooooooooooooooxXMMMMMNOollllllcccccc:::::::::::::::dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:;;;;;;;;;;;;;;;;;;;;;;;;;;:;cxXWMMMNkc::::::::::::::::::::cccccclOWMMMNklllllloooooooooooooooooooooxKWMMMWXxlllllccccccc:::::::::::::::::oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:;;;;;;;;;;;;;;;;;;;;;;;;;;;;::dKWMMMNkc:::::::::::::::::::::cccclOWMMMNklllllllllllllllllooolllllldKWMMMW0dlllcccccccc:::::::::::::::::::oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0l;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::lOWMMWNxc:::::::::::::::::::::::cckWMMWNxccclllllllllllllllllllllld0WMMMNOocccccccccc:::::::::::::::::::::dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ckNMMMXx::::::::::::::::::::::::ckNMMWNxccccccccclllllllllllllllo0WMMWXxlcccccccc:::::::::::::::::::::::ckWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:;:dXWMMXxc::::::::::::::::::::::ckNMMWXxcccccccccccccccccccccccoOWMMW0dcccccc:::::::::::::::::::::::::::dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:o0WMWXxc:;:::::::::::::::::::ckNMMWXd::::ccccccccccccccccccoOWMMNOoccc:::::::::::::::::::::::::::;;:oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:lONMMNxc:;::::::::::::::::::ckNMMWXd::::::::::::ccccccccco0WMWXkl:::::::::::::::::::::::::::::::;:oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:ckNMMNkc:;:::::::::::::::::ckWMMWNd::::::::::::::::::::o0WMWXdc::::::::::::::::::::::::::::::::cxXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMMMMMMMWXxc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:xXWMNkc::::::::::::::::::ckWMMMNx:::::::::::::::::::o0WMWKo::::::::::::::::::::::::::::::;::oONMMMMMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKocokKNWMMMMMMMMMWKxc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:dKWMNOl:;:;:::::::::::::cOWMMMNx::::::::::::::::::oKWMW0l::::::::::::::::::::::::::::;:::oOXWMMMMMMMMMWN0kdlxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,''';cdOXWMMMMMMMMWXkl:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:o0WMW0l:;;;::;;::::::::cOWMMMNx:::::::::::::::::dXWMNOl::::::::::::::::::::::::::;;;:cdONWMMMMMMMWNKOdl:;;;lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo'.''''',:ox0NWMMMMMMWNOdc;;;;;;;;;;;;;;;;;;;;;;;;;;;;:l0WMWKo:;;;;;:::::::::l0WMMMWk:::::::::::::::cxXWWNkc:::::::::::::::::::::::::;;;:lxKNMMMMMMWWXOxoc:;;;;;;:kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc...'''''',,;cdOKNWMMMMMWKxl:;;;;;;;;;;;;;;;;;;;;;;;;;;;lONMWXd:;;;;;;;;;;;::lKWMMMWkc:::::::::::::ckNMWXxc:::::::::::::::::::::::;:::cdOXWMMMMMWN0kdc:;;;;;;;;;;:xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc....'''''',,,,;:lx0XWMMMMWN0xl:;;;;;;;;;;;;;;;;;;;;;;;;;ckNMMNkc;;;;;;;;;;;:oKMMMMWOc::::::::::::lONMWXdc:::::::::::::::::::;;::;:cokKWMMMMWNKOxl:;;;;;;;;;;;;;;:xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl.....'''''',,,,,,,;cdkKNWMMMWX0xl:;;;;;;;;;;;;;;;;;;;;;;;cxNMMNOl:;;;;;;;;;;dXMMMMW0l:::::::::;:o0WMWKd::::::::::::::::::::;;;:cokKNWMMMWX0xoc:;;;;;;;;;;;;;;;;;:kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd'......'''''',,,,,,,,;:lxOXWWMMWX0xl:;;;;;;;;;;;;;;;;;;;;;:xXWMW0o:;;;;;;;;:dNMMMMMKl:;;:;;;;::dXWMWKo:;;;::::::::::;;;;;;;:cokKNWMMWNKOdl:;;;;;;;;;;;;;;;;;;;;;cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;.......'''''',,,,,,,,,,;;cokKNWMWWX0xl:;;;;;;;;;;;;;;;;;;;:dXWMWKd:;;;;;;;:xNMMMMMKo::;;:;;:cxXWMWKo:;;::;;;:;;;:;;;;;;:cokKNWMMWX0xoc:;;;;;;;;;;;;;;;;;;;;;;;;oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo.........'''''',,,,,,,,,,,;;:lxOXWWWWN0koc;;;;;;;;;;;;;;;;;:dXWMWXxc;;;;;;:kWMMMMMXd:;;;;;:lONMMW0o:;;;;;;;;;;;;;;;;:ldOKNWMWNKkdl:;;;;;;;;;;;;;;;;;;;;;;;;;;;:kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:.........'''''',,,,,,,,,,;;,;;;cokKNWWWNKOdl:;;;;;;;;;;;;;;:dXWMMNOl;;;;;cOWMMMMMNx:;;;;:oKWMMW0l:;;;:;;;;;;;;;:cox0XWWWWX0xoc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;..........'''''',,,,,,,,,,,;;;;;;:lxOXWMMWX0xoc;;;;;;;;;;;;:dKWMMWKo:;;;l0WMMMMMWk:;;;cxXWMMW0l:;;;;;;;;;;;:ldkKNWMMNKOdl:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:..........''''''',,,,,,,,,,,,;;;;;;;cdkKNWWWNKOdl:;;;;;;;;;:dXWMMWXxc;;oKMMMMMMWOc;:lONWMMW0l;;;;;;;;;:cox0XWWMWN0koc:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c'..........'''''',,,,,,,,,,,,,;;;;;;;;:ox0NWMMWNKkoc:;;;;;;:dXWMMMNOl:dXMMMMMMW0l:o0WMMMW0l;;;;;;;:ldOKNWMMWXOxl:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:xXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXx;..........'''''''',,,,,,,,,,,,;;;;;;;;;:ldOXWMMWWX0xoc;;;;:dXWMMMWKxONMMMMMMMXkxXWMMMW0l;;;;:ldkKNWMMWNKkdc:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo,...........''''''',,,,,,,,,,,,;;;;;;;;;;;cdkKNWMMWNXOxoc;:dXMMMMMWWMMMMMMMMMWWMMMMWKo;:cok0XWWMMWN0xoc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd:'.........'''''''',,,,,,,,,,,,;;;;;;;;;;;;:ok0NWMMMWNKOxdOWMMMMMMMMMMMMMMMMMMMMMNkdk0XWWMMMWX0xl:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:okXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXko;'.........''''''',,,,,,,,,,,,,,,;;;;;;;;;;:ox0NWMMMMWNWMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMWXOdl:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:lx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdc;'.......'''''''',,,,,,,,,,,,,,;;;;;;;;;;;:lx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdl:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:cldkKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kxolc::;;;;;;::::::::::::::ccccccccccccccccldKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOdlccccccccccccccccccccccccccccccccclllloodxO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWNNNNNNNXXXXXXKKKKKK0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKKKKKKXXXXXXNNNNNNNWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0kxxxxxxdddddoooooollllllllccccccccccc:::::::::cd0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkoc:::cccccccllllllloooooodddddddxxxxxxkkkkkkkkOOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;......................'''''''''',,,,,,,,,,;lxKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0dc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,;oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c'.......................'''''''''',,,,;lx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdc;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,:dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXx;.........................'''''''';lx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdc;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,;lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo;...........................';lx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXOdl;;,,,,,,,,,,,,,,,,,,,,,,,,,,,ckXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;'.....................';lkKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xl:;,,,,,,,,,,,,,,,,,,,,,;cxXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl;'..............',cdOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdc;,,,,,,,,,,,,,',;cdONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdl:;,''''',:ldOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdl:;,,,,,;:cox0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK0OO00KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK00O00KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWMMMMMMMMMMMMWWWWWWMMMMMMMWWWWWWMMMMMMMMMMMMWWWWWWMMMMMMMMMMMMMMWWWWWWMMMMMMMMMMWWWWWWWMMMMMMMMMMMWWWWWMMMMMMMMMMMWWWWWWWMMMMWWWWWWWWWWWWWWWWWWWWMMMMMMMWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx;;;;oXMMMMMMMMMMNx;;;;dNMMMMMWk:;;;oXMMMMMMMMMMNx:;;;dXMMMMMMMMMMMMXo;;;;oXMMMMMMMMWOc;;;:kWMMMMMMMMMKl;;;l0MMMMMMMMMWOc;;;cOWMMXd;;;;;;;;;;;;;;;;;;lKMMMMMNd;;;:xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.   ;KMMMMMMMMMMNc.   :XMMMMMWo.   ,0MMMMMMMMMMNl.   :KMMMMMMMMMMMNl.    .lNMMMMMMMMK:.   ,0MMMMMMMMNo.   .cXMMMMMMMMK:.  .:KMMMK:                  'OMMMMMX:   .lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.   ;KMMMMMMMMMMNc.   :KMMMMMNo.   ,0MMMMMMMMMMNc.   :KMMMMMMMMMMNd.      .dNMMMMMMMMO,   .lXMMMMMMWk'     .xWMMMMMMNo.   'OMMMMK:   .':ccccccccccccoKMMMMMX:   .cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.   ;KMMMMMMMMMMNc.   :XMMMMMNo.   ;0MMMMMMMMMMNc.   :KMMMMMMMMMWx.  ...   .xWMMMMMMMWd.   .xWMMMMMK:.      ,0MMMMMMO'   .dWMMMMK:   .lNMMMMMWMWMMMMMMMMMMMX:   .cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.   ;KMMMMMMMMMMNc.   :XMMMMMNo.   ;0MMMMMMMMMMNc.   :KMMMMMMMMWk'   'xd.   'kWMMMMMMMXc.  .;0MMMMNo.  ...  .cXMMMMXc.  .cXMMMMMK:   .lNMMMMMMMMMMMMMMMMMMMX:   .cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.   'okxxkkxxxxkd,.   :XMMMMMNo.   ;0MMMMMMMMMMNc.   :KMMMMMMMWO,   .dWNo.   ,OWMMMMMMM0,   .lNMMWk'   ,l,   .xWMMWd.   ,OMMMMMMK:   .'looooooooOWMMMMMMMMMX:   .cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.    ............     :XMMMMMNo.   ,0MMMMMMMMMMNc.   :KMMMMMMM0;.  .oNMMXl.  .;0MMMMMMMWx.   'kWMK:.  .dNx.   ;0MM0,   .xWMMMMMMK:             .lNMMMMMMMMMX:   .cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.    .............    :XMMMMMNo.   ,0MMMMMMMMMMNl.   :KMMMMMMK:.  .lXMMMMKc.  .:KMMMMMMMNl.  .:KNo.  .cXMXc.  .lNXc.  .lXMMMMMMMK:    .'''''''',dNMMMMMMMMMX:   .cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.   'dkkkkkkkkkkx,    :XMMMMMWo.   ,OMMMMMMMMMMXc.   :XMMMMMXc.   .:oooooo:.   .cOXMMMMMMK;.  .ox'   ,0MMM0;.  .dd.  .;0MMMMMMMMK:   .cKXXXXXXXXNMMMMMMMMMMX:   .cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.   ;KMMMMMMMMMMNc.   :XMMMMMWx.   .oNMMMMMMMMWk'   .oNMMMMNl.                  ..lNMMMMMWk'   ...  .xWMMMWx.  ....  .xWMMMMMMMMK:   .lNMMMMMMMMMMMMMMMMMMMX:   .cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.   ;KMMMMMMMMMMNc.   :XMMMMMMXc.   .l0NWMMMWKd,.  .,0MMMMNo.  ..'''''''''''..    .oNMMMMMNo.      .lXMMMMMNl.      .lNMMMMMMMMMK:   .lNMMWMMMMMMMMWWMMMMMMX:   .cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.   ;KMMMMMMMMMMNc.   :XMMMMMMMK:.   ..,:ccc;'.   .,OWMMMWd.   'dXXXXXXXXXXXKo.    .xWMMMMMK:.    .;0MMMMMMMK;.    .;KMMMMMMMMMMK:   .':ccccccccccccckWMMMMX:   .cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc.   ;KMMMMMMMMMMNc.   :XMMMMMMMMXd;.            .,oKWMMMWk'   .dNMMMMMMMMMMMMNo.    'kWMMMMMO'    .xWMMMMMMMWk'    'kWMMMMMMMMMMK:                  .cNMMMMX:   .cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx;;;;oXMMMMMMMMMMNx;;;;dXMMMMMMMMMMNOdc;,'''',;cokXWMMMMMXo;;;:xNMMMMMMMMMMMMMMXd;;;;;oXMMMMMWx:;;;dNMMMMMMMMMNx;;;:xNMMMMMMMMMMMXd;;;;;;;;;;;;;;;;;;:xNMMMMNd;;;:xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNWMMMMMMMMMMMMWNNNNWMMMMMMMMMMMMMMWNXK00KXNWMMMMMMMMMWNNNNNWMMMMMMMMMMMMMMMMWNNNNNNWMMMMMMWNNNNWMMMMMMMMMMMWNNNNWMMMMMMMMMMMMMWNNNNNNNNNNNNNNNNNNNWMMMMMMWNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

    IMPORTANT ADDRESS OF THE KERNEL OF HUAWEI: 
    004015CE <- THE BIG SWITCH
    004019CC <- MAIN
*/


int __cdecl alg(char* IMEI, unsigned int* SECURITY_CODE)

{
    int iVar1;

    iVar1 = calcula(IMEI, 2);
    switch (iVar1) {
    case 0:
        calculo_0(IMEI, SECURITY_CODE, 2);
        return iVar1;
    case 1:
        calculo_2(IMEI, (byte*)SECURITY_CODE, 2);
        return iVar1;
    case 2:
        calculo_3(IMEI, SECURITY_CODE, 2);
        return iVar1;
    case 3:
        calculo_4(IMEI, SECURITY_CODE, 2);
        return iVar1;
    case 4:
        calculo_5(IMEI, (char*)SECURITY_CODE);
        return iVar1;
    case 5:
        calculo_6((int)IMEI, (char*)SECURITY_CODE, 2);
        return iVar1;
    case 6:
        calculo_7((int)IMEI, SECURITY_CODE, 2);
        return iVar1;
    default:
        *SECURITY_CODE = 0x4e202d20;
        SECURITY_CODE[1] = 0x2d20412f;
        SECURITY_CODE[2];//*(undefined*)(param_2 + 2) = 0; //FIX
        return iVar1;
    }
}


int main()
{
    printf(R"EOF(
MMMMSSSSSSSSSSSSSSSSSMSS;.     .dMMMMSSSSSSMMSSSSSSSSS
MMSSSSSSSMSSSSSMSSSSMMMSS."-.-":MMMMMSSSSMMMMSSMSSSMMS
MSSSSSSSMSSSSMMMSSMMMPTMM;"-/\":MMM^"     MMMSSMMMSSMM
SSSSSSSMMSSMMMMMMMMMP-.MMM :  ;.;P       dMMMMMMMMMP' 
SSMSSSMMMSMMMMMMMMMP   :M;`:  ;.'+"""t+dMMMMMMMMMMP   
MMMSSMMMMMMMMPTMMMM"""":P `.\// '    ""^^MMMMMMMP'    
MMMMMMPTMMMMP="TMMMsg,      \/   db`c"  dMMMMMP"      
MMMMMM  TMMM   d$$$b ^          /T$; ;-/TMMMP         
MMMMM; .^`M; d$P^T$$b          :  $$ ::  "T(          
MMMMMM   .-+d$$   $$$;         ; d$$ ;;  __           
MMMMMMb   _d$$$   $$$$         :$$$; :MmMMMMp.        
MMMMMM"  " T$$$._.$$$;          T$P.'MMMSSSSSSb.      
MMM`TMb   -")T$$$$$$P'       `._ ""  :MMSSSMMP'       
MMM / \    '  "T$$P"           /     :MMMMMMM         
MMSb`. ;                      "      :MMMMMMM         
MMSSb_lSSSb.      \ `.   .___.       MMMMMMMM         
MMMMSSSSSSSSb.                     .MMMMMMMMM         
MMMMMMMMMMMSSSb                  .dMMMMMMMMM'         
MMMMMMMMMMMMMSS;               .dMMMMMMMMMMP          
MMMMMMMMMMMMMb`;"-.          .dMMMMMMMMMMP'           
MMMMMMMMMMMMMMb    ""--.___.dMMMMMMMMMP^"  KEOWU :)
)EOF");
    char IMEI[] = { '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1' };
    unsigned int SECURITY_CODE[20];
    int a = alg(IMEI, SECURITY_CODE);
}